import {summary,items} from '/model.mjs';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'Not recorded':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
const num=v=>v==null?'—':new Intl.NumberFormat('en-IN').format(v);
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let S,view='overview',query='',from='',to='',segment='',status='',page=1;
const names={overview:'Overview',orders:'Orders',dispatches:'Dispatch',jobs:'Make & buy',customers:'Customers',products:'Product catalogue',suppliers:'Suppliers',complaints:'Quality & complaints',invoices:'Finance',emails:'Business inbox',trends:'Trends & reports',sources:'Data & connections'};
const icons=['◈','▤','↗','⚙','◎','▦','◇','⊙','₹','✉','↝','⇄'];
const descriptions={overview:'A clear view of your domestic business.',orders:'From incoming order to fulfilled commitment.',dispatches:'Record shipments by part. Partial deliveries stay visible.',jobs:'Manufacturing and supplier purchasing in one work queue.',customers:'Distributor, shop and direct customer relationships.',products:'Source-backed prices, effective dates and product details.',suppliers:'Supplier performance and marka records.',complaints:'Track investigation, corrective action and verified closure.',invoices:'Recorded invoices and collections. Tally connection pending.',emails:'Domestic business correspondence, ready for review.',trends:'See how each department is changing over time.',sources:'Import data, check freshness and download a private backup.'};
// Every editable field has an explicit type. No financial defaults are inferred.
const schema={
 orders:[['id','Order ID'],['customer','Customer'],['contact','Contact person'],['date','Received date','date'],['po','PO number'],['poDate','PO date','date'],['promised','Original promised dispatch','date'],['expected','Revised expected dispatch','date'],['channel','Channel','select:Unknown,Direct,Distributor,Shop'],['segment','Vehicle segment','select:Unknown,2W,3W,Mixed'],['status','Workflow','select:Unverified,Confirmed,Manufacturing,Purchasing,Ready,Cancelled'],['owner','Responsible person'],['value','Source order value (₹)','number'],['items','Parts and quantities · SKU x10 | SKU x5','textarea'],['notes','Notes / revision reason','textarea']],
 dispatches:[['id','Dispatch line ID'],['orderId','Order ID','order'],['sku','Part code'],['qty','Quantity','number'],['date','Dispatch date','date'],['transporter','Transporter'],['lr','LR / tracking number'],['notes','Notes','textarea']],
 jobs:[['id','Job / purchase ID'],['orderId','Linked order','order'],['type','Fulfilment','select:Manufacture,Buy'],['sku','Part code'],['supplier','Supplier / production department'],['qty','Planned quantity','number'],['completed','Completed / received quantity','number'],['date','Start / PO date','date'],['due','Expected completion','date'],['actual','Actual completion','date'],['status','Status','select:Planned,In progress,Awaiting material,Quality check,Completed,Cancelled'],['owner','Responsible person'],['notes','Notes','textarea']],
 customers:[['id','Customer ID'],['name','Business name'],['contact','Contact person'],['channel','Channel','select:Unknown,Direct,Distributor,Shop'],['city','City'],['mobile','Phone'],['email','Email'],['gst','GST number'],['status','Status','select:Needs verification,Approved,On hold'],['creditDays','Agreed credit days','number'],['discount','Agreed trade discount (%)','number'],['effective','Terms effective date','date'],['notes','Commercial terms / FOC / approval reference','textarea']],
 products:[['id','BLW part code'],['name','Part name'],['segment','Vehicle segment','select:2W,3W'],['model','Vehicle / engine model'],['unit','Price unit'],['mrp','List price (₹)','number'],['effective','Price effective date','date'],['source','Price source'],['notes','Specifications / price basis','textarea']],
 suppliers:[['id','Supplier ID'],['name','Supplier name'],['marka','Marka'],['rating','Source star rating (0–5)','number'],['period','Rating period'],['source','Rating source'],['notes','Quality / delivery observations','textarea']],
 complaints:[['id','Complaint ID'],['customer','Customer'],['contact','Contact person'],['orderId','Linked order','order'],['date','Received date','date'],['sku','Part / model'],['qty','Affected quantity','number'],['status','Status','select:New,Investigating,Action in progress,Closed'],['owner','Responsible person'],['due','Target closure','date'],['description','Complaint description','textarea'],['action','Root cause and corrective action','textarea'],['closed','Verified closure date','date'],['source','Evidence reference']],
 invoices:[['id','Invoice number'],['customer','Customer'],['orderId','Linked order','order'],['date','Invoice date','date'],['due','Agreed due date','date'],['amount','Invoice total (₹)','number'],['paid','Total received (₹)','number'],['paidDate','Latest receipt date','date'],['source','Tally / source reference'],['notes','Receipt references / commercial adjustments','textarea']],
 emails:[['id','Message ID'],['subject','Subject'],['date','Email date','date'],['category','Department'],['status','Review status','select:Review,Actioned,Dismissed'],['owner','Responsible person'],['due','Follow-up date','date'],['action','Follow-up / linked record ID','textarea']]
};
async function api(url,body){const r=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',6000);}
async function refresh(){S=await api('/api/state');render();}
async function init(){try{const session=await api('/api/session');if(!session.authenticated){$('#app').innerHTML=`<section class="auth card"><div class="brand">BLW<i>.</i></div><p class="eyebrow">Domestic operations · 2W / 3W</p><h1>${session.setup?'Set up your workspace':'Welcome back'}</h1><p class="muted">${session.setup?'Create your owner password to open your private business dashboard.':'Sign in to your private business dashboard.'}</p><form id="login"><label for="password">Owner password</label><input id="password" type="password" minlength="12" required autocomplete="${session.setup?'new-password':'current-password'}" placeholder="At least 12 characters"><p class="error" id="login-error"></p><button class="primary">${session.setup?'Create password & open':'Open dashboard'}</button></form><p class="login-note">Business data is stored on this computer. This address is a local preview; phone access needs secure hosting.</p></section>`;$('#login').onsubmit=async e=>{e.preventDefault();try{await api('/api/login',{password:$('#password').value});await refresh();}catch(e){$('#login-error').textContent=e.message;}};}else await refresh();}catch(e){$('#app').textContent='Could not open BLW: '+e.message;}}
function selected(rows){return rows.filter(r=>{const d=r.date||'';return(!from||d>=from)&&(!to||d<=to)&&(!segment||r.segment===segment)&&(!status||r.status===status)&&(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));});}
function filteredState(){return {...S,orders:selected(S.orders),dispatches:selected(S.dispatches),jobs:selected(S.jobs),complaints:selected(S.complaints),invoices:selected(S.invoices)};}
const pill=(s,t='')=>`<span class="tag ${t}">${esc(s||'Not recorded')}</span>`;
function render(){
 $('#app').innerHTML=`<aside><div class="brand">BLW<i>.</i></div><p class="subbrand">DOMESTIC OPERATIONS</p><nav>${Object.entries(names).map(([k,n],i)=>`<button data-view="${k}" class="${view===k?'active':''}"><span>${icons[i]}</span>${n}</button>`).join('')}</nav><div class="aside-foot">2 & 3 wheeler parts<br>Manufacture · Supply · Service<br><br>Inventory tracking deferred</div></aside><main><header><div class="crumb">BLW Engine Valves / <strong>${names[view]}</strong></div><div class="account"><span class="muted">Owner workspace</span><div class="avatar">B</div><button class="small" id="logout">Sign out</button></div></header><div class="page"><div class="title-row"><div><div class="eyebrow">Domestic business / ${esc(today)}</div><h1>${names[view]}</h1><div class="muted">${descriptions[view]}</div></div><div>${schema[view]&&view!=='emails'?`<button class="primary" id="add">＋ Add ${view==='dispatches'?'dispatch line':'record'}</button>`:'<button id="refresh">↻ Refresh dashboard</button>'}</div></div><div id="content"></div><p class="tabs-footer">INR · India time · Source order value is not invoiced revenue · Last loaded ${esc(new Date(S.serverTime).toLocaleString('en-IN'))}</p></div></main>`;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;query='';status='';segment='';page=1;render();});$('#logout').onclick=async()=>{await api('/api/logout',{});await init();};if($('#add'))$('#add').onclick=()=>edit(view);if($('#refresh'))$('#refresh').onclick=()=>refresh().catch(e=>toast(e.message));
 draw();
}
function filters(dateFilter=true){return `<div class="toolbar"><input class="search" id="search" placeholder="Search ${names[view].toLowerCase()}…" value="${esc(query)}" aria-label="Search records">${dateFilter?`<label>From <input id="from" type="date" value="${from}"></label><label>To <input id="to" type="date" value="${to}"></label>`:''}<button id="clear">Clear filters</button><button id="export">Export CSV</button></div>`;}
function bindFilters(){if(!$('#search'))return;$('#search').oninput=e=>{query=e.target.value;page=1;draw(true);};for(const id of ['from','to'])if($('#'+id))$('#'+id).onchange=e=>{if(id==='from')from=e.target.value;else to=e.target.value;page=1;draw();};$('#clear').onclick=()=>{query='';from='';to='';status='';segment='';page=1;draw();};$('#export').onclick=exportRows;}
function metric(label,value,note){return `<div class="card"><div class="metric-label">${label}</div><div class="metric">${value}</div><div class="kpi-foot">${note}</div></div>`;}
function grouped(rows,key,fn){const m=new Map();for(const r of rows){const k=r[key];if(!k)continue;m.set(k,(m.get(k)||0)+fn(r));}return [...m].sort((a,b)=>a[0].localeCompare(b[0]));}
function line(rows,label,format=num){if(!rows.length)return `<div class="empty">No dated records available for this trend.</div>`;const max=Math.max(1,...rows.map(r=>r[1])),minX=35,w=600,h=180;const first=Date.parse(rows[0][0]),last=Date.parse(rows.at(-1)[0]);const pts=rows.map((r,i)=>[minX+(rows.length===1?w/2:(Date.parse(r[0])-first)/Math.max(1,last-first)*w),20+h-r[1]/max*h]);return `<svg class="chart" viewBox="0 0 660 240" role="img" aria-label="${esc(label)}">${[0,.5,1].map(n=>`<line x1="35" x2="635" y1="${20+h-n*h}" y2="${20+h-n*h}"></line><text x="0" y="${24+h-n*h}">${esc(format(max*n))}</text>`).join('')}<polygon class="fill" points="${pts[0][0]},200 ${pts.map(p=>p.join(',')).join(' ')} ${pts.at(-1)[0]},200"></polygon><polyline points="${pts.map(p=>p.join(',')).join(' ')}"></polyline>${pts.map((p,i)=>`<circle tabindex="0" cx="${p[0]}" cy="${p[1]}" r="3.5"><title>${esc(rows[i][0])}: ${esc(format(rows[i][1]))}</title></circle>${i===0||i===rows.length-1||i%Math.max(1,Math.ceil(rows.length/5))===0?`<text x="${p[0]}" y="225" text-anchor="middle">${esc(rows[i][0].slice(5))}</text>`:''}`).join('')}</svg><div class="muted">${esc(label)} · hover or focus points for exact values</div>`;}
function bars(rows,format=num){const max=Math.max(1,...rows.map(r=>r[1]));return rows.length?rows.map(([name,v])=>`<div class="bar-row"><div class="bar-label"><span>${esc(name)}</span><strong>${esc(format(v))}</strong></div><div class="bar-track"><div style="width:${v/max*100}%"></div></div></div>`).join(''):'<div class="empty">No records available yet.</div>';}
function overview(){const f=filteredState(),m=summary({...f,dispatches:S.dispatches},today);const daily=grouped(f.orders.filter(o=>o.status!=='Cancelled'),'date',o=>o.value||0);const top=grouped(f.orders,'customer',o=>o.value||0).sort((a,b)=>b[1]-a[1]).slice(0,5);return `${filters()}<div class="kpis">${metric('Recorded order value',money(m.value),`${m.orders} orders · before commercial verification`)}${metric('Orders without full dispatch record',num(m.open),'Based on recorded shipment lines')}${metric('Overdue commitments',num(m.late),`${m.undated} open orders have no commitment date`)}${metric('Recorded receivables',f.invoices.length?money(m.receivables):'Not connected',f.invoices.length?'Invoices less recorded receipts':'Import or enter invoice data from Tally')}</div><div class="grid"><section class="card"><div class="card-head"><div><h2>Order value over time</h2><div class="muted">Recorded order intake · INR</div></div>${pill('Source data')}</div>${line(daily,'Order value',v=>v>=100000?(v/100000).toFixed(1)+'L':v>=1000?(v/1000).toFixed(0)+'k':num(v))}</section><section class="card"><div class="card-head"><div><h2>Leading customers</h2><div class="muted">By recorded order value</div></div></div>${bars(top,money)}</section></div><div class="grid equal"><section class="card"><h2>Needs your attention</h2>${[[m.undated+' orders need a dispatch commitment','Enter an agreed date to make delay reporting meaningful.'],[S.emails.filter(e=>e.status==='Review').length+' business emails to review','Email summaries are not counted as individual complaints.'],[duplicateCount()+' possible duplicate orders','Review matching customer and part quantities before confirmation.'],[m.complaints+' open complaint records','Email-reported issues remain in the business inbox until verified.']].map(([h,p])=>`<div class="activity"><span class="dot"></span><div><h3>${h}</h3><p class="muted">${p}</p></div></div>`).join('')}</section><section class="card"><h2>Recent order intake</h2>${f.orders.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(o=>`<div class="activity"><span class="dot"></span><div><h3>${esc(o.customer)}</h3><p class="muted">${esc(o.id)} · ${esc(o.date)} · ${money(o.value)}</p></div></div>`).join('')}</section></div>`;}
function duplicateCount(){const seen=new Set();let n=0;for(const o of S.orders){const k=o.customer.toLowerCase()+'|'+items(o.items).map(i=>i.sku+':'+i.qty).sort().join('|');if(seen.has(k))n++;else seen.add(k);}return n;}
const columns={orders:[['id','Order'],['customer','Customer'],['date','Received'],['value','Source value'],['expected','Expected dispatch'],['status','Workflow']],dispatches:[['id','Dispatch'],['orderId','Order'],['sku','Part'],['qty','Qty'],['date','Dispatched'],['lr','LR / tracking']],jobs:[['id','Work reference'],['type','Make / buy'],['sku','Part'],['qty','Planned'],['completed','Completed'],['due','Due'],['status','Status']],customers:[['name','Customer'],['contact','Contact'],['city','City'],['channel','Channel'],['status','Verification']],products:[['id','Part code'],['name','Part'],['segment','Segment'],['mrp','List price'],['unit','Unit'],['source','Price source']],suppliers:[['name','Supplier'],['marka','Marka'],['rating','Stars / 5'],['period','Period'],['source','Source']],complaints:[['id','Complaint'],['customer','Customer'],['sku','Part'],['date','Received'],['status','Status'],['owner','Owner']],invoices:[['id','Invoice'],['customer','Customer'],['date','Invoice date'],['due','Due'],['amount','Invoice total'],['paid','Received']]};
function table(kind){const rows=selected(S[kind]),cols=columns[kind];const visible=rows.slice((page-1)*25,page*25);return `${filters(['orders','dispatches','jobs','complaints','invoices'].includes(kind))}${kind==='orders'?`<div class="notice">${duplicateCount()} possible repeats across all orders. Source status is unverified until confirmed. Delivery promises are entered per order.</div>`:''}${kind==='invoices'?'<div class="notice">Tally is not connected. Cash discount, interest, FOC and credit holds require verified terms; this screen does not post accounting entries.</div>':''}<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}<th>Details</th></tr></thead><tbody>${visible.map(r=>`<tr>${cols.map(([k])=>`<td>${['value','amount','paid','mrp'].includes(k)?money(r[k]):k==='status'?pill(r[k],r[k]==='Unverified'||r[k]==='Needs verification'?'amber':''):k==='expected'?esc(r.expected||r.promised||'Not set'):esc(r[k]??'—')}</td>`).join('')}<td><button class="small" data-edit="${esc(r.id)}">Open →</button></td></tr>`).join('')}</tbody></table>${rows.length?'':`<div class="empty"><strong>No ${names[kind].toLowerCase()} records yet</strong>${query||from||to?'Try clearing the filters.':'Add a verified record to begin tracking this department.'}</div>`}</div><div class="actions"><span class="muted">${rows.length} records · page ${page} of ${Math.max(1,Math.ceil(rows.length/25))}</span><button id="prev" ${page===1?'disabled':''}>Previous</button><button id="next" ${page*25>=rows.length?'disabled':''}>Next</button></div>`;}
function inbox(){return `${filters()}<div class="notice">Only reviewed domestic business messages are included. This is an imported snapshot, not continuous mailbox sync. Genuine staff emails are retained. No emails are sent by this dashboard.</div><div class="mail">${selected(S.emails).map(e=>`<article class="card"><div class="card-head"><div><div class="eyebrow">${esc(e.category)} · ${esc(e.date)}</div><h2>${esc(e.subject)}</h2><div class="muted">${esc(e.from)} · ${esc(e.mailbox)}</div></div>${pill(e.status,e.status==='Review'?'amber':'')}</div><p>${esc(e.summary)}</p><p class="muted">${esc(e.caution)}</p><details><summary>Read source excerpt</summary><div class="mail-body">${esc(e.body)}</div></details><div class="actions"><a href="https://mail.google.com/mail/u/0/#all/${encodeURIComponent(e.thread)}" target="_blank" rel="noopener">Open original email ↗</a><button data-edit="${esc(e.id)}" class="small">Review / assign</button></div></article>`).join('')||'<div class="empty">No business messages match this filter.</div>'}</div>`;}
function trends(){const f=filteredState();const plots=[['Order intake',grouped(f.orders.filter(o=>o.status!=='Cancelled'),'date',o=>o.value||0),'Source order value · INR'],['Dispatch quantities',grouped(f.dispatches,'date',d=>d.qty),'Recorded units dispatched'],['Manufacturing / purchasing',grouped(f.jobs,'actual',j=>j.completed||0),'Units completed or received on actual completion date'],['Complaints received',grouped(f.complaints,'date',()=>1),'Verified complaint records; excludes email summary counts'],['Invoice value',grouped(f.invoices,'date',i=>i.amount),'Invoiced value · INR']];return `${filters()}<div class="grid equal">${plots.map(([title,rows,label])=>`<section class="card"><h2>${title}</h2>${line(rows,label)}</section>`).join('')}<section class="card"><h2>Workflow distribution</h2>${bars(grouped(f.orders,'status',()=>1))}</section></div><div class="notice">Charts reflect recorded data only. No curve is drawn for a department without dated records. Customer, SKU and segment searches filter each dataset independently.</div>`;}
function sources(){return `<div class="grid equal"><section class="card"><h2>Source snapshots</h2>${S.sources.map(s=>`<div class="source-row"><h3>${esc(s.name)}</h3><div class="muted">Read ${esc(s.at)}<br>${esc(s.note)}</div></div>`).join('')}<div class="source-row"><h3>Tally</h3><div class="muted">Not connected. Enter verified invoices now; a live bridge still needs your Tally environment.</div></div><div class="source-row"><h3>Daily refresh</h3><div class="muted">Scheduled for 9:00 AM India time through this Codex task. Requires this host and the connected accounts to be available. Source timestamps above show actual completed reads.</div></div><div class="source-row"><h3>Second mailbox</h3><div class="muted">Not yet verified through the available connection.</div></div></section><section class="card"><h2>Import a sheet export</h2><p class="muted">Download the matching Google Sheet tab as CSV. Existing IDs are preserved. Changed source records are logged for review instead of overwriting your work.</p><label>Sheet type <select id="import-kind"><option value="orders">Orders</option><option value="complaints">Complaints</option><option value="customers">Registrations</option></select></label><p><input id="csv" type="file" accept=".csv,text/csv" aria-label="Select CSV export"></p><button class="primary" id="import">Import CSV</button><p class="muted">Excludes shivyansh, kundan and test in business/contact names. Personal email and unrelated export activity are excluded from the mailbox snapshot.</p><hr><h2>Private backup</h2><p class="muted">Contains business records and change history. Keep it in your private storage.</p><a href="/api/backup">Download backup JSON ↓</a></section></div><section class="card"><h2>Change history</h2><div class="table-wrap"><table><thead><tr><th>When</th><th>Action</th><th>Department</th><th>Reference</th></tr></thead><tbody>${S.audit.slice(0,40).map(a=>`<tr><td>${esc(a.at)}</td><td>${esc(a.action)}</td><td>${esc(a.kind)}</td><td>${esc(a.record_id)}</td></tr>`).join('')}</tbody></table></div></section>`;}
function draw(keepFocus=false){const pos=$('#search')?.selectionStart;$('#content').innerHTML=view==='overview'?overview():view==='trends'?trends():view==='emails'?inbox():view==='sources'?sourceReviews()+sources():table(view);bindFilters();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(view,S[view].find(r=>r.id===b.dataset.edit)));if($('#prev'))$('#prev').onclick=()=>{page--;draw();};if($('#next'))$('#next').onclick=()=>{page++;draw();};if($('#import'))$('#import').onclick=importCSV;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewSource(b.dataset.kind,b.dataset.review));if(keepFocus&&$('#search')){$('#search').focus();$('#search').setSelectionRange(pos,pos);}}
function edit(kind,record){const r=record||{id:kind.toUpperCase().slice(0,3)+'-'+crypto.randomUUID().slice(0,8),status:kind==='orders'?'Unverified':kind==='emails'?'Review':undefined};const fields=schema[kind];const dialog=$('#editor');dialog.innerHTML=`<div class="card-head"><div><div class="eyebrow">${names[kind]}</div><h2>${record?'Record details':'New record'}</h2></div><button id="close" aria-label="Close editor">×</button></div>${kind==='orders'&&record?`<p class="muted">${esc(r.received)} · ${esc(r.source)}<br>Dispatched: ${num(S.dispatches.filter(d=>d.orderId===r.id).reduce((s,d)=>s+d.qty,0))} of ${num(items(r.items).reduce((s,i)=>s+i.qty,0))} units.</p>`:''}<form id="record-form"><div class="form-grid">${fields.map(([key,label,type='text'])=>{const val=r[key]??'';let input;if(type.startsWith('select:')){input=`<select name="${key}">${type.slice(7).split(',').map(v=>`<option ${v===val?'selected':''}>${v}</option>`).join('')}</select>`;}else if(type==='order'){input=`<input name="${key}" list="order-list" value="${esc(val)}"><datalist id="order-list">${S.orders.map(o=>`<option value="${esc(o.id)}">${esc(o.customer)}</option>`).join('')}</datalist>`;}else if(type==='textarea'){input=`<textarea name="${key}">${esc(val)}</textarea>`;}else input=`<input name="${key}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(val)}" ${record&&key==='id'||kind==='orders'&&key==='promised'&&r.promised?'readonly':''}>`;return `<label class="${type==='textarea'?'wide':''}">${esc(label)}${input}</label>`;}).join('')}</div><p class="error" id="save-error" role="alert"></p><div class="actions"><button type="button" id="cancel">Cancel</button><button class="primary">Save record</button></div></form>`;dialog.showModal();$('#close').onclick=$('#cancel').onclick=()=>dialog.close();$('#record-form').onsubmit=async e=>{e.preventDefault();const next={...r,...Object.fromEntries(new FormData(e.target))};for(const [k,,type] of fields)if(type==='number')next[k]=next[k]===''?null:Number(next[k]);try{await api('/api/record',{kind,record:next,version:record?.version});dialog.close();await refresh();toast('Saved to your private database');}catch(e){$('#save-error').textContent=e.message;}};}
function parseCSV(text){const rows=[];let row=[],s='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){s+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(s);s='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(s);rows.push(row);row=[];s='';}else s+=c;}if(q)throw Error('Unclosed quote in CSV');if(s||row.length){row.push(s);rows.push(row);}if(rows[0]?.[0])rows[0][0]=rows[0][0].replace(/^\uFEFF/,'');return rows;}
async function importCSV(){try{const file=$('#csv').files[0];if(!file)throw Error('Select a CSV file first');const result=await api('/api/import',{kind:$('#import-kind').value,rows:parseCSV(await file.text())});await refresh();toast(`${result.added} added, ${result.unchanged} unchanged, ${result.excluded} test records excluded, ${result.conflicts} source changes need review.`);}catch(e){toast(e.message);}}
function exportRows(){const rows=selected(S[view]||S.orders);if(!rows.length){toast('No records to export');return;}const keys=[...new Set(rows.flatMap(Object.keys))].filter(k=>k!=='body');const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const csv=[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');const u=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='BLW-'+view+'.csv';a.click();URL.revokeObjectURL(u);}
function sourceReviews(){const pending=Object.keys(schema).flatMap(kind=>(S[kind]||[]).filter(r=>r.sourceReview).map(r=>({kind,r})));return pending.length?'<section class="card"><h2>Source changes awaiting review</h2>'+pending.map(({kind,r})=>'<div class="source-row"><strong>'+esc(r.id)+'</strong><p class="muted">Changed fields: '+esc(r.sourceReview.fields.join(', '))+'</p><button data-kind="'+kind+'" data-review="'+esc(r.id)+'">Compare changes</button></div>').join('')+'</section>':'';}
function reviewSource(kind,id){const r=S[kind].find(r=>r.id===id),p=r.sourceReview,d=$('#editor');d.innerHTML='<h2>Review source change</h2><p class="muted">'+esc(id)+'</p><table><tr><th>Field</th><th>Current</th><th>Source</th></tr>'+p.fields.map(k=>'<tr><td>'+esc(k)+'</td><td>'+esc(r[k])+'</td><td>'+esc(p.incoming[k])+'</td></tr>').join('')+'</table><p class="error" id="review-error"></p><div class="actions"><button id="review-close">Close</button><button id="review-keep">Keep current</button><button id="review-accept" class="primary">Accept source values</button></div>';d.showModal();$('#review-close').onclick=()=>d.close();const save=async accept=>{try{await api('/api/source-review',{kind,id,version:r.version,accept});d.close();await refresh();toast('Source review saved');}catch(e){$('#review-error').textContent=e.message;}};$('#review-keep').onclick=()=>save(false);$('#review-accept').onclick=()=>save(true);}
init();

